import streamlit as st
import sys
import os
from docx import Document
from io import BytesIO

# --- 1. SYSTEM SETUP: PATH INJECTION ---
current_dir = os.path.dirname(os.path.abspath(__file__))
if current_dir not in sys.path:
    sys.path.append(current_dir)

# --- 2. MODULAR IMPORTS ---
try:
    from agents.auditor import perform_audit
    from agents.tutor import generate_syllabus
    from agents.storyteller import draft_star_bullets
    from agents.voice_filter import refine_to_human_voice
except ModuleNotFoundError as e:
    st.error(f"Critical Error: Ensure 'agents' folder has __init__.py and is lowercase. {e}")
    st.stop()

# --- 3. SESSION STATE (The App's Memory) ---
# This ensures results stay on the screen after you click Download
if 'analysis_results' not in st.session_state:
    st.session_state.analysis_results = None

# --- 4. UTILITY: WORD DOC GENERATOR ---
def create_docx(text):
    doc = Document()
    doc.add_heading('Revised Resilience Narrative', 0)
    doc.add_paragraph("This content was generated by the Career Orchestrator Multi-Agent Platform.")
    doc.add_paragraph("-" * 20)
    doc.add_paragraph(text)
    
    buffer = BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer

# --- 5. STREAMLIT UI SETUP ---
st.set_page_config(page_title="Career Orchestrator", page_icon="🤖", layout="wide")
st.title("🚀 Career Orchestrator: Multi-Agent Platform")
st.markdown("### Bridging the 'Entry-Level' Gap with Authenticity")

# Sidebar for API Key & Settings
with st.sidebar:
    st.header("🔑 Credentials")
    deepseek_api_key = st.text_input("DeepSeek API Key", type="password")
    st.info("Get your key at platform.deepseek.com")
    st.divider()
    if st.button("Clear Dashboard & Memory"):
        st.session_state.analysis_results = None
        st.rerun()

# --- 6. INPUT SECTION ---
col1, col2 = st.columns(2)
with col1:
    st.subheader("📄 Your Master Resume")
    resume_input = st.text_area("Paste your background here:", height=250, 
                               placeholder="Include your 3.9 GPA, USPS experience, etc.")
with col2:
    st.subheader("💼 Target Job Description")
    jd_input = st.text_area("Paste the job you want:", height=250,
                           placeholder="Paste the full JD requirements here.")

# --- 7. EXECUTION PIPELINE ---
if st.button("Run Multi-Agent Optimization"):
    if not deepseek_api_key:
        st.error("Please enter your DeepSeek API Key in the sidebar.")
    elif not resume_input or not jd_input:
        st.warning("Please provide both a resume and a job description.")
    else:
        try:
            with st.status("🛠️ Running Agentic Pipeline...", expanded=True) as status:
                
                # Agent 1: The Auditor
                st.write("Agent 1: Identifying Gaps...")
                gaps = perform_audit(resume_input, jd_input, deepseek_api_key)
                
                # Mock Match Score Logic (In Phase 3, we will parse this from the LLM)
                match_score = 82 
                
                # Agent 2: The Tutor
                st.write("Agent 2: Building your 48-hour syllabus...")
                syllabus = generate_syllabus(gaps, deepseek_api_key)

                # Agent 3: The Storyteller
                st.write("Agent 3: Drafting STAR narratives...")
                raw_stories = draft_star_bullets(resume_input, gaps, jd_input, deepseek_api_key)
                
                # Agent 4: The Voice Filter
                st.write("Agent 4: Humanizing the tone...")
                final_narrative = refine_to_human_voice(raw_stories, deepseek_api_key)
                
                # SAVE TO MEMORY
                st.session_state.analysis_results = {
                    "gaps": gaps,
                    "syllabus": syllabus,
                    "narrative": final_narrative,
                    "score": match_score
                }
                status.update(label="✅ Optimization Complete!", state="complete", expanded=False)
                    
        except Exception as e:
            st.error(f"Pipeline Error: {e}")

# --- 8. PERSISTENT DISPLAY LOGIC ---
# This section keeps the data on the screen after the Download button rerun
if st.session_state.analysis_results:
    data = st.session_state.analysis_results
    
    st.divider()
    
    # --- Match Gauge Section ---
    st.header(f"📊 Resume-to-JD Match: {data['score']}%")
    if data['score'] >= 80:
        st.success("✅ Strong Technical Match. Focus on STAR Optimization below.")
        st.progress(data['score'] / 100)
    elif data['score'] >= 65:
        st.warning("⚠️ Narrative Bridge Required. Highlighting your Resilience & Soft Skills.")
        st.progress(data['score'] / 100)
    else:
        st.error("🛑 Significant Technical Gap. We recommend the Tutor Syllabus first.")
        st.progress(data['score'] / 100)

    # --- Results Tabs ---
    tab1, tab2, tab3 = st.tabs(["🚩 Gap Audit", "📚 Learning Syllabus", "✍️ Final Narrative"])
    
    with tab1:
        st.markdown(data['gaps'])
    
    with tab2:
        st.markdown(data['syllabus'])
    
    with tab3:
        st.info(data['narrative'])
        # Generate the Word Doc in memory
        doc_file = create_docx(data['narrative'])
        
        st.download_button(
            label="📄 Download Revised Resume Bullets (.docx)",
            data=doc_file,
            file_name="Resilience_Narrative_Revision.docx",
            mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
        )
